### ISSUE TITLE
list with fomated items produces invalid html

### ISSUE THREAD

**Issue by bernhard-efler** [nadar/quill-delta-parser#8] opened 2019-05-20 13:15 UTC
**Describe the bug**

an list with formatted items misses the `<ol></ol>` tags in html output

**The delta code which generates the Problem**

```
{"ops":[{"attributes":{"bold":true},"insert":"bold"},{"attributes":{"list":"ordered"},"insert":"\n"},{"attributes":{"italic":true},"insert":"italic"},{"attributes":{"list":"ordered"},"insert":"\n"},{"attributes":{"underline":true},"insert":"underline"},{"attributes":{"list":"ordered"},"insert":"\n"},{"attributes":{"strike":true},"insert":"strike"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"\nnormal Text\n"}]}
```

**The expected html output the delta should produce**

```
<ol><li><strong>bold</strong></li><li><em>italic</em></li><li><u>underline</u></li><li><s>strike</s></li></ol><p><br></p><p>normal Text</p>
```

**Comment by nadar** [comment] 2019-05-20 13:18
Hi @bernhard-efler, i will do some research. Thanks for the repport. I assume you are running the latest version? There are already some tests, but maybe there is something special in your case.

https://github.com/nadar/quill-delta-parser/blob/c8610a7863f414919edf1f7a2b45d7703839f70e/tests/ParserTest.php#L29

**Comment by bernhard-efler** [comment] 2019-05-20 13:28
I've played a little with the deltas: It looks like it happens when to there is only one operation for the list item.

a shorter not working delta: `[{"insert":"Title "},{"attributes":{"bold":true},"insert":"bold"},{"attributes":{"list":"ordered"},"insert":"\n"}]`

shure, i am using the last github version

**Comment by nadar** [comment] 2019-05-20 13:29
thanks for the more detailed test delta, will do some research

**Comment by nadar** [comment] 2019-05-20 13:40
So obviously:

```
[{"insert":"Title "},{"attributes":{"bold":true},"insert":"bold"},{"attributes":{"list":"ordered"},"insert":"\n"}]
```

should return

```
<ol><li>Title <strong>bold</strong></li></ol>
```

but returns

```
<li>Title <strong>bold</strong></li>
```

right?

**Comment by bernhard-efler** [comment] 2019-05-20 13:45
Yes, that is precisely the current & the expected output

**Comment by nadar** [comment] 2019-05-20 13:57
Yes, indeed i can confirm this bug.

**Comment by nadar** [comment] 2019-05-20 15:00
@bernhard-efler The issue should be fixed, would you please test again with the dev-master? If everything is fixed i will do a release.

**Comment by bernhard-efler** [comment] 2019-05-20 15:12
sorry, it is not full fixed. The long example in my first post does still not work.
the list is closed after the first list item
`<ol><li><strong>bold</strong></li></ol><li>...`

**Comment by nadar** [comment] 2019-05-20 18:32
Yes indeed, thank you for the report.

**Comment by nadar** [comment] 2019-05-20 19:07
hey @bernhard-efler i just added some more tests and (hopefully) improved the behavior of list element, please let me know if everything works as expected. Your example is now part of the test:

https://github.com/nadar/quill-delta-parser/blob/master/tests/ParserTest.php#L42

**Comment by bernhard-efler** [comment] 2019-05-21 08:38
Hi, I have some more test cases where some are failing:

Text before a list is not parsed correct at the moment

```
$deltas[] = [
    '{"ops":[{"insert":"item 1"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"item 2"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"item 3"},{"attributes":{"list":"ordered"},"insert":"\n"}]}',
    '<ol><li>item 1</li><li>item 2</li><li>item 3</li></ol>'
];
$deltas[] = [
    '{"ops":[{"insert":"item 1"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"item 2"},{"attributes":{"list":"bullet"},"insert":"\n"},{"insert":"item 3"},{"attributes":{"list":"bullet"},"insert":"\n"}]}',
    '<ul><li>item 1</li><li>item 2</li><li>item 3</li></ul>'
];
$deltas[] = [
    '{"ops":[{"insert":"Text\nList Item 1"},{"attributes":{"list":"ordered"},"insert":"\n"}]}',
    '<p>Text</p><ol><li>List Item 1</li></ol>'
];
$deltas[] = [
    '{"ops":[{"insert":"Text\n"},{"attributes":{"bold":true},"insert":"List Item 1"},{"attributes":{"list":"ordered"},"insert":"\n"}]}',
    '<p>Text</p><ol><li><strong>List Item 1</strong></li></ol>'
];
$deltas[] = [
    '{"ops":[{"insert":"Text\n"},{"attributes":{"bold":true},"insert":"List "},{"insert":"Item"},{"attributes":{"bold":true},"insert":" 1"},{"attributes":{"list":"ordered"},"insert":"\n"}]}',
    '<p>Text</p><ol><li><strong>List </strong>Item<strong> 1</strong></li></ol>'
];
$deltas[] = [
    '{"ops":[{"insert":"Text\n"},{"attributes":{"bold":true},"insert":"List "},{"insert":"Item"},{"attributes":{"bold":true},"insert":" 1"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"Item 2"},{"attributes":{"list":"ordered"},"insert":"\n"}]}',
    '<p>Text</p><ol><li><strong>List </strong>Item<strong> 1</strong></li><li>Item 2</li></ol>'
];
$deltas[] = [
    '{"ops":[{"attributes":{"bold":true},"insert":"List "},{"insert":"Item"},{"attributes":{"bold":true},"insert":" 1"},{"attributes":{"list":"ordered"},"insert":"\n"},{"insert":"Item 2"},{"attributes":{"list":"ordered"},"insert":"\n"}]}',
    '<ol><li><strong>List </strong>Item<strong> 1</strong></li><li>Item 2</li></ol>'
];
```

**Comment by nadar** [comment] 2019-05-21 08:41
Which one is failing? Or what does your array contain? The expected html or the result for the delta code?

**Comment by bernhard-efler** [comment] 2019-05-21 08:44
its the delta with the expecting html
`{"ops":[{"insert":"Text\n"},{"attributes":{"bold":true},"insert":"List Item 1"},{"attributes":{"list":"ordered"},"insert":"\n"}]}`
should generate 
`<p>Text</p><ol><li><strong>List Item 1</strong></li></ol>` but I get `<ol><li>Text<strong>List Item 1</strong></li></ol>`

**Comment by nadar** [comment] 2019-05-21 09:49
Thanks, indeed. Its interesting how small delta content breaks the code, while large complex code won't. Thank you for providing those delta codes, which makes the parser more stable.

**Comment by nadar** [comment] 2019-05-22 07:01
Your tests are passing now, but i detected another while working. It's really hard to handle those list elements because it's unclear to say when a list element ends and when the whole list ends. Quill Delta code is definitely a pain in certain situations ;-)

**Comment by nadar** [comment] 2019-05-26 18:30
hey @bernhard-efler i just added some more tests including a new way on how to parse list elements, hopefully things are better now. please let me know if you can find some more bugs. Otherwise i will do version 1.3.0 release. Thanks

**Comment by nadar** [comment] 2019-05-28 06:36
I am going to close this issue, if you have any further issues please create an issues. Thanks again for the error report.

**Closed by nadar** 2019-05-28 06:36 UTC
Labels: bug
